services:
    message.queue_manager:
        class: Jasuwienas\MessageBundle\Service\QueueManagerService
        arguments: ["@doctrine.orm.entity_manager", "%message.queue_object_class%"]
    message.queue_manager.process:
        class: Jasuwienas\MessageBundle\Service\ProcessQueueService
        arguments: ["@message.queue_manager", "@service_container", "@translator"]
    message.sender.smtp:
        class: Jasuwienas\MessageBundle\Service\Senders\SmtpMailSenderService
        arguments: ["@mailer", '%smtp_mailer_user%']
    message.sender.freshmail:
        class: Jasuwienas\MessageBundle\Service\Senders\FreshMailSenderService
        arguments: ['%freshmail_api_host%', '%freshmail_api_prefix%', '%freshmail_api_api_key%', '%freshmail_api_secret_key%']